[package]
name = "segy_rust"
version = "0.1.0"
authors = ["Fabian Andres Perdomo Laguna <faperdomola@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
segy_core = { path = "segy_core" }